site_name: "stats-agents"
site_url: https://ericmjl.github.io/stats-agents

docs_dir: docs/

# For more configuration on the theme, see https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/
theme:
  name: material
  icon:
    logo: "fontawesome/solid/book"
  features:
    - instant
    - tabs
  language: en

# Navigation structure
nav:
  - Home: index.md

  - API Reference: api.md
  - R2D2 Framework:
    - Overview: r2d2m2_summary.md
    - GLM Variant: r2d2_glm_summary.md
    - Shrinkage Variant: r2d2_shrinkage_summary.md
  - Design:
    - Requirements: design/requirements.md
  - Blog: blog.md

plugins:
  - search
  - mknotebooks:
      execute: true
      write_markdown: true
      allow_errors: false
      timeout: 1200
      binder: true
      binder_service_name: "gh"
      binder_branch: "master"
      binder_ui: "lab"

# Taken from here: https://squidfunk.github.io/mkdocs-material/extensions/codehilite/
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - markdown.extensions.attr_list

extra_css:
  - apidocs.css

extra_javascript:
  - config.js

repo_name: "ericmjl/stats-agents"
repo_url: "https://github.com/ericmjl/stats-agents"

extra:
  social:
    - icon: "fontawesome/brands/github"
      link: "https://github.com/ericmjl"
